[project]
name = "mongodb-ml-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastparquet>=2025.12.0",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
    "pymongo>=4.16.0",
    "scikit-learn>=1.8.0",
]
